// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1nR8XA3xa3vH2u7fX6pIxtNKRhJKZDTM',
    appId: '1:902970221615:web:4f445269db92b5b00dd2da',
    messagingSenderId: '902970221615',
    projectId: 'sg-chat-8e346',
    authDomain: 'sg-chat-8e346.firebaseapp.com',
    storageBucket: 'sg-chat-8e346.appspot.com',
    measurementId: 'G-PLM479FJ7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW4Cgtr5GzTXnNoGtpxCQxFsonY9a1fas',
    appId: '1:902970221615:android:3382c504572b50e60dd2da',
    messagingSenderId: '902970221615',
    projectId: 'sg-chat-8e346',
    storageBucket: 'sg-chat-8e346.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK18MBVMsmtnOQb0F6Y-JU2Zfv5WkMnLs',
    appId: '1:902970221615:ios:8c7b1e30104f14c60dd2da',
    messagingSenderId: '902970221615',
    projectId: 'sg-chat-8e346',
    storageBucket: 'sg-chat-8e346.appspot.com',
    iosClientId: '902970221615-assgee0n7252s0oqknmferrqbf2k92rd.apps.googleusercontent.com',
    iosBundleId: 'com.example.sgpaypoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK18MBVMsmtnOQb0F6Y-JU2Zfv5WkMnLs',
    appId: '1:902970221615:ios:8c7b1e30104f14c60dd2da',
    messagingSenderId: '902970221615',
    projectId: 'sg-chat-8e346',
    storageBucket: 'sg-chat-8e346.appspot.com',
    iosClientId: '902970221615-assgee0n7252s0oqknmferrqbf2k92rd.apps.googleusercontent.com',
    iosBundleId: 'com.example.sgpaypoint',
  );
}
